version: "3"

services:

  # -------------------- CanvasBoard APIs Express Container -------------------- #

  canvasboard-apis:
    image: "canvasboard-apis"
    build:
      context: ./APIs
      dockerfile: Dockerfile
    container_name: canvasboard-apis
    environment:
      PORT: 4000
    ports:
      - "4000:4000"
    networks:
      - docker_net
    restart: unless-stopped


  # -------------------- MongoDB -------------------- #

  mongodb:
    image: mongo
    container_name: mongodb
    env_file:
      - ./apis/.env
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - docker_net
    restart: unless-stopped

networks:
  docker_net:
    driver: bridge

volumes:
  mongodb-data: