name: Canvasboard Backend CI/CD

on:
  push:
     branches:
      - master
      - unitTesting
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}      
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}       
    - run: npm ci
      working-directory: ./APIs
#     - run: npm run build
#       working-directory: ./APIs
#     - run: npm test
# ----------------DOCKER SETUP AND PUSH ---------------------------
    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and psuh to docker
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./APIs
        file: ./APIs/Dockerfile
        push: true
        tags: goliakshay357/canvasboard-backend:latest

    - name: Image Digest
      run: echo ${{ steps.docker_build.outputs.digest }}

# -----------------DEPLOYMENT IN ANSIBLE ---------------------------
  deploy:

    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/ansible
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        SSH_USER: ${{ secrets.SSH_USER }}

